# Generated by Django 2.2.24 on 2021-12-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openedx_plugin_cms", "0002_courseaudit"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseaudit",
            name="f_xblock_customized_html",
            field=models.TextField(
                blank=True,
                help_text="Raw html contents of this block",
                max_length=255,
                null=True,
                verbose_name="XBlock Customized HTML",
            ),
        ),
        migrations.AlterField(
            model_name="courseaudit",
            name="r_publication_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="The original publication date of this block",
                null=True,
                verbose_name="Publication Date",
            ),
        ),
    ]
