# Generated by Django 3.2.12 on 2022-02-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingsites',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es-419', 'Español (Latinoamérica)'), ('pt-br', 'Português (Brasil)'), ('pt-pt', 'Português (Portugal)'), ('it-it', 'Italiano (Italia)'), ('fr', 'Français')], help_text='A language code. Examples: en, en-US, es, es-419, es-MX', max_length=20),
        ),
    ]
